### ISSUE TITLE
[Epic]: Documentation Revise Cycle

### ISSUE THREAD

**Issue by samricotta** [cosmos/cosmos-sdk-docs#139]
Due to the rapid changes in the SDK it has left the documentation being fragmented and out of date. The documentation needs some love but mostly needs newcomers not to be confused or put off by the fragmentation.

I have divided each of the tasklists into categories of the documentation to keep it organised:

```[tasklist]
### Learn
- [ ] https://github.com/cosmos/cosmos-sdk/issues/20173
- [ ] https://github.com/cosmos/cosmos-sdk/issues/20174
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/153
- [ ] https://github.com/cosmos/cosmos-sdk/issues/17320
- [ ] Accounts to x/accounts revise
- [ ] Accounts diagram replace
- [ ] Minimise GRPC section in transactions
- [ ] Store Diagrams
- [ ] Reduce Encoding large code reference
- [ ] Reduce ocap code large reference
- [ ] https://github.com/cosmos/cosmos-sdk/issues/20176
- [ ] Introduction
```

```[tasklist]
### Build
- [ ] https://github.com/cosmos/cosmos-sdk/issues/20171
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/144
```

```[tasklist]
### Tutorials
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/140
- [ ] x/accounts
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/116
```

This is a working list and shall be added to as time goes on.
```[tasklist]
### General
- [ ] https://github.com/cosmos/cosmos-sdk/issues/11625
```
