### ISSUE TITLE
[Epic]: Phase 2 Documentation

### ISSUE THREAD

**Issue by samricotta** [cosmos/cosmos-sdk-docs#84]
```[tasklist]
### Tutorials Page
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/88
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/90
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/92
- [x] Clear https://github.com/cosmos/sdk-tutorials
- [x] Add the workshop code for oracle to the tutorial repo ^^
- [x] Add the workshop code for Mitigating front running to the tutorial repo ^^
- [x] Add tutorial into link at bottom of the page
```

```[tasklist]
### Home page for each topic
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/95
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/96
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/97
```

```[tasklist]
### ABCI++ Page
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/87
- [x] Add documentation for vote extensions
- [x] Add documentation for prepare and process proposal
```

```[tasklist]
### 0.50 documentation to update
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/104
```

```[tasklist]
### Misc
- [ ] https://github.com/cosmos/cosmos-sdk-docs/issues/112
```
